### ISSUE TITLE
use secret-annotations for instructions

### ISSUE THREAD

**Issue by Blaimi** [Blaimi/imagepullsecret-serviceaccount-patcher#3]
Currently, the secrets injected into service-accounts by ips-sa-p are controlled by setting an environment-variable (`REGISTRY_SECRET_NAMES`).

Instead of using a runtime-configuration of the service, this could be done by annotating the secret. The annotations could look like the following and orientate on [mittwald/kubernetes-replicator](https://github.com/mittwald/kubernetes-replicator)

The value of the annotation is split into a list of comma-, newline- or space-separated (for `|`&`>` yaml-syntax) list containing namespace/sa-name tuples with regular expressions. The regexes are interpreted separately. Since `/` is not allowed as a character for k8s-namespaces or sa-names, there shouldn't be a conflict or escaping-problem.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret-replica-to-everywhere
  annotations:
    imagepullsecret-serviceaccount-patcher.v1.blaimi.de/inject-to: ".*/.*"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret-replica-to-selected
  annotations:
    imagepullsecret-serviceaccount-patcher.v1.blaimi.de/inject-to: |
      ^(?!kube-).*/default
      ^review-.*/.*
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
```
